
services:
  server:
    build: .
    container_name: quiz-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: quiz-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
