apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-server
  template:
    metadata:
      labels:
        app: quiz-server
    spec:
      containers:
        - name: quiz-server
          image: raymarvin/quiz-server:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: quiz-server-env

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-server-service
spec:
  type: NodePort
  selector:
    app: quiz-server
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
